[versions]
mcp = "2.0.1-SNAPSHOT"
picocli = "4.7.7"
sqlite = "3.53.2.0"
vineflower = "1.11.2"
tiny-remapper = "0.10.4"
junit = "6.1.0"
shadow = "9.5.1"
slf4j = "2.0.16"
tomcat = "11.0.2"
servlet = "6.1.0"

[libraries]
mcp = { module = "io.modelcontextprotocol.sdk:mcp", version.ref = "mcp" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
tiny-remapper = { module = "net.fabricmc:tiny-remapper", version.ref = "tiny-remapper" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
tomcat-embed-core = { module = "org.apache.tomcat.embed:tomcat-embed-core", version.ref = "tomcat" }
servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "servlet" }
