[versions]
mcp = "2.0.1-SNAPSHOT"
picocli = "4.7.7"
h2 = "2.4.240"
vineflower = "1.12.0"
tiny-remapper = "0.14.0"
mapping-io = "0.9.0"
junit = "6.1.2"
shadow = "9.6.1"
slf4j = "2.0.18"
tomcat = "11.0.24"

[libraries]
mcp = { module = "io.modelcontextprotocol.sdk:mcp", version.ref = "mcp" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
tiny-remapper = { module = "net.fabricmc:tiny-remapper", version.ref = "tiny-remapper" }
mapping-io = { module = "net.fabricmc:mapping-io", version.ref = "mapping-io" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
tomcat-embed-core = { module = "org.apache.tomcat.embed:tomcat-embed-core", version.ref = "tomcat" }
